spring:
  application:
    name: demo
  data:
    mongodb:
      username: user
      password: password
      host: localhost
      port: 27017
      database: miniautorizador
      authentication-database: admin